jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true
          environment-file: environment.yml
          environment-name: py_app_base

      # Linux and macOS
      - name: Run Python
        shell: bash -l {0}
        run: |
          python -m pytest
